server:
    port: 8085
spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123123
  application:
    name: service-neo4j
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1